export { default as  HeroSection } from "./heroSection/HeroSection";
export { default as  SupportSection } from "./supportSection/SupportSection";
export { default as  ServiceSection } from "./serviceSection/ServiceSection";
export { default as  ServicePage } from "./servicePage/servicePage";
export { default as  ProjectsSection } from "./projectsSection/ProjectsSection";
export { default as  PortfolioSection } from "./portfolioSection/PortfolioSection";
export { default as  FooterSection } from "./footerSection/FooterSection";
export { default as  PortfolioPage } from "./portfolioPage/PortfolioPage";
export { default as  Pagenotfound } from "./pageNotfound/Pagenotfound";